#!/bin/bash -x
root=$(cd $(dirname $0) && pwd)
cd $root

./api-problem-submit $1 $2
cat result2.json | jq -r "."

if [ $(cat result2.json | jq -r ".ok") = "true" ]; then
  savename="challenges/$1"
  cp $2 "$savename.txt"
  cat result2.json | jq -r "." > "$savename.json"
fi
